version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      python: 3.9
    commands:
      - python3 -m venv /root/venv
      - . /root/venv/bin/activate
      - python3 -m pip install --upgrade pip
      - pip3 install aws-sam-cli
  pre_build:
    commands:
      - export LC_ALL="en_US.UTF-8"
      - locale-gen en_US en_US.UTF-8
      - dpkg-reconfigure locales
  build:
    commands:
      - sam build
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
cache:
  paths:
    - '/root/venv/**/*'
    - '/root/.cache/pip/**/*'
    - '/root/.gradle/wrapper/**/*'