AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Search Workspace Service API and Handlers
Globals:
  Function:
    Timeout: 60
    MemorySize: 1800
    Environment:
      Variables:
        ELASTICSEARCH_REGION: "eu-west-1"
        SCOPE_IDENTIFIER: 'https://api.sws.aws.sikt.no/scopes'
        API_GATEWAY_URL: !Sub 'https://api.${CustomDomain}'
        BACKUP_BUCKET_NAME: !Sub '${BackupBucketName}'
        BACKUP_ROLE_ARN: !GetAtt SWSSnapshotRepoRole.Arn
        TEST_PARAMETER: !Ref TestParameter

  Api:
    Cors:
      AllowMethods: "'PUT, GET,OPTIONS,DELETE,POST'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Parameters:
  ElasticSearchSize:
    Type: String
    Default: small
    AllowedValues:
      - small
      - large
  UserPoolDomainPrefix:
    Type: String
    Default: sws-auth-dev
    Description: The prefix for the Cognito domain that hosts the sign-up and sign-in pages for your application.
  CustomDomain:
    Type: String
    Description: Custom API to connect this lambda to
  BackupBucketName:
    Type: String
    Description: Name of the S3 bucket for olensearch buckups
  TestParameter:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/SWS/Temp/Parameter'

Conditions:
  LargeElasticSearch:  !Equals [ !Ref ElasticSearchSize, 'large' ]


Resources:
  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup

  ElasticSearchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [ lambda.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      Policies:
        - PolicyName: writeLog
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'
        - PolicyName: readIdentitySecret
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:IdentityServiceSecret*'

  SWSLambdaTriggerRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: writeLog
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'
        - PolicyName: allOpenSearch
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - es:ESHttpDelete
                  - es:ESHttpPost
                  - es:ESHttpPut
                  - es:ESHttpGet
                  - es:ESHttpHead
                Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*'
        - PolicyName: invokeLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"

  SWSCognitoRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: writeLog
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'
        - PolicyName: invokeLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
        - PolicyName: cognitoCreateScopeAndClient
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:ListResourceServers
                  - cognito-idp:UpdateResourceServer
                  - cognito-idp:CreateUserPool
                  - cognito-idp:ListUserPools
                  - cognito-idp:CreateUserPoolClient
                  - cognito-idp:DescribeUserPoolClient
                  - cognito-idp:ListUserPoolClients
                Resource: "*"

  SWSSnapshotRepoRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
              AWS:
                - "*"
            Action: sts:AssumeRole
      Policies:
        - PolicyName: writeLog
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'
        - PolicyName: allOpenSearch
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - es:ESHttpDelete
                  - es:ESHttpPost
                  - es:ESHttpPut
                  - es:ESHttpGet
                  - es:ESHttpHead
                Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*'
        - PolicyName: invokeLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - iam:PassRole
                Resource: "*"
        - PolicyName: snapshotS3Repo
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub 'arn:aws:s3:::${BackupBucketName}/*'
        - PolicyName: lists3Bucket
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub 'arn:aws:s3:::${BackupBucketName}'




  SWSApi:
    Type: AWS::Serverless::Api
    Properties:
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod
      EndpointConfiguration: REGIONAL
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: ./docs/openapi.yaml

  CustomCodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service: [ codedeploy.amazonaws.com ]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda

  IndexHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: Index handler for indeces within a workspace
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          OPENSEARCH_ENDPOINT_PROTOCOL: "https"
          OPENSEARCH_ENDPOINT_ADDRESS: !GetAtt SWSOpenSearch.DomainEndpoint
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
      Events:
        PutEvent:
          Type: Api
          Properties:
            Method: put
            Path: /{resource+}
            RestApiId: !Ref SWSApi
        HeadEvent:
         Type: Api
         Properties:
           Method: head
           Path: /{resource+}
           RestApiId: !Ref SWSApi
        DeleteEvent:
          Type: Api
          Properties:
            Method: delete
            Path: /{resource+}
            RestApiId: !Ref SWSApi
        GetEvent:
          Type: Api
          Properties:
            Method: get
            Path: /{resource+}
            RestApiId: !Ref SWSApi
        PostEvent:
          Type: Api
          Properties:
            Method: post
            Path: /{resource+}
            RestApiId: !Ref SWSApi
      Handler: no.sikt.sws.IndexHandler::handleRequest
      Runtime: java11
      Role: !GetAtt SWSLambdaTriggerRole.Arn


  WorkspaceHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: Handler for workspace - listing indeces and showing account identifier
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          OPENSEARCH_ENDPOINT_PROTOCOL: "https"
          OPENSEARCH_ENDPOINT_ADDRESS: !GetAtt SWSOpenSearch.DomainEndpoint
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Method: get
            Path: /
            RestApiId: !Ref SWSApi
      Handler: no.sikt.sws.WorkspaceHandler::handleRequest
      Runtime: java11
      Role: !GetAtt SWSLambdaTriggerRole.Arn

  CognitoHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: Handler for Cognito - create new users / workspaces
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          OPENSEARCH_ENDPOINT_PROTOCOL: "https"
          OPENSEARCH_ENDPOINT_ADDRESS: !GetAtt SWSOpenSearch.DomainEndpoint
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
      Handler: no.sikt.sws.CognitoHandler::handleRequest
      Runtime: java11
      Role: !GetAtt SWSCognitoRole.Arn

  RegisterSnapshotRepoHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: Handler for registering repository for manual snapshots. Needs to be run from Lambda test in console.
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          OPENSEARCH_ENDPOINT_PROTOCOL: "https"
          OPENSEARCH_ENDPOINT_ADDRESS: !GetAtt SWSOpenSearch.DomainEndpoint
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
      Handler: no.sikt.sws.RegisterSnapshotRepoHandler::handleRequest
      Runtime: java11
      Role: !GetAtt   SWSSnapshotRepoRole.Arn


  SnapshotTakingHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: Handler for registering snapshots manually. Needs to be run from Lambda test in console.
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          OPENSEARCH_ENDPOINT_PROTOCOL: "https"
          OPENSEARCH_ENDPOINT_ADDRESS: !GetAtt SWSOpenSearch.DomainEndpoint
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
      Handler: no.sikt.sws.SnapshotTakingHandler::handleRequest
      Runtime: java11
      Role: !GetAtt   SWSSnapshotRepoRole.Arn
      Events:
        ScheduledEventTakingSnapshot:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)

  SnapshotRestorationHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: Handler for Restoring from a snapshot
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          OPENSEARCH_ENDPOINT_PROTOCOL: "https"
          OPENSEARCH_ENDPOINT_ADDRESS: !GetAtt SWSOpenSearch.DomainEndpoint
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
      Handler: no.sikt.sws.SnapshotTakingHandler::handleRequest
      Runtime: java11
      Role: !GetAtt   SWSSnapshotRepoRole.Arn



  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      MfaConfiguration: "OFF"
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: false
      UsernameConfiguration:
        CaseSensitive: true
      UserPoolName: "SWSUserPool"

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: !Ref UserPoolDomainPrefix

  ResourceServerScopes:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      Identifier: https://api.sws.aws.sikt.no/scopes
      Name: Scopes for backend
      Scopes:
        - ScopeDescription: Scope for accessing workspaces
          ScopeName: workspace
        - ScopeDescription: Scope for accessing sondres workspace
          ScopeName: workspace-sondre
        - ScopeDescription: Scope for accessing stigs workspace
          ScopeName: workspace-stig
        - ScopeDescription: Scope for accessing marinas workspace
          ScopeName: workspace-marina
        - ScopeDescription: Scope for accessing fredriks workspace
          ScopeName: workspace-fredrik
      UserPoolId: !Ref UserPool

  BackendApplicationSondreClient:
    DependsOn: ResourceServerScopes
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - https://api.sws.aws.sikt.no/scopes/workspace
        - https://api.sws.aws.sikt.no/scopes/workspace-sondre
      ClientName: BackendApplicationSondreClient
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: true
      IdTokenValidity: 15
      AccessTokenValidity: 15
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes

  BackendApplicationFredrikClient:
    DependsOn: ResourceServerScopes
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - https://api.sws.aws.sikt.no/scopes/workspace
        - https://api.sws.aws.sikt.no/scopes/workspace-fredrik
      ClientName:   BackendApplicationFredrikClient
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: true
      IdTokenValidity: 15
      AccessTokenValidity: 15
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes


  BackendApplicationStigClient:
    DependsOn: ResourceServerScopes
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - https://api.sws.aws.sikt.no/scopes/workspace
        - https://api.sws.aws.sikt.no/scopes/workspace-stig
      ClientName: BackendApplicationStigClient
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: true
      IdTokenValidity: 15
      AccessTokenValidity: 15
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes

  BackendApplicationMarinaClient:
    DependsOn: ResourceServerScopes
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - https://api.sws.aws.sikt.no/scopes/workspace
        - https://api.sws.aws.sikt.no/scopes/workspace-marina
      ClientName: BackendApplicationMarinaClient
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: true
      IdTokenValidity: 15
      AccessTokenValidity: 15
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
  SwsBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Sub api.${CustomDomain}
      RestApiId: !Ref SWSApi
      Stage: !Ref SWSApi.Stage

  SWSOpenSearch:
    Type: AWS::OpenSearchService::Domain
    Properties:
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt ElasticSearchRole.Arn
            Action:
              - es:ESHttpPost
              - es:ESHttpGet
              - es:ESHttpPut
              - es:ESHttpDelete
              - es:ESHttpHead
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
            Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*'
      ClusterConfig: !If [ LargeElasticSearch,
        {
          DedicatedMasterEnabled: true,
          DedicatedMasterType: t2.medium.search,
          DedicatedMasterCount: 3,
          InstanceCount: 2,
          ZoneAwarenessEnabled: false,
          InstanceType: t2.medium.search
        },
        {
          DedicatedMasterEnabled: false,
          InstanceCount: 1,
          ZoneAwarenessEnabled: false,
          InstanceType: t2.medium.search
        }
      ]
      EngineVersion: "OpenSearch_1.3"
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: gp2
      CognitoOptions:
        Enabled: false
