plugins {
    id 'nva-sws.java-conventions'
}

dependencies {
    api(nvaCatalog.aws.java.sdk.core)
    api(nvaCatalog.aws.lambda.core)
    api(nvaCatalog.jackson.annotations)
    api(nvaCatalog.jackson.core)
    api(nvaCatalog.jackson.databind)
    api(nvaCatalog.slf4j.api)
    api(nvaLibs.apigateway)
    api(nvaLibs.core)
    implementation('software.amazon.awssdk:aws-core')
    implementation('software.amazon.awssdk:cognitoidentityprovider')
    implementation('software.amazon.awssdk:regions')
    implementation('software.amazon.awssdk:sdk-core')
    implementation('software.amazon.awssdk:url-connection-client')
    implementation(libs.jsonld) {
        exclude group: 'org.apache.httpcomponents', module: 'httpcore-osgi'
        exclude group: 'org.apache.httpcomponents', module: 'httpclient-osgi'
        because("Duplicates dependencies from AWS SDKs")
    }
    implementation(nvaCatalog.aws.sdk2.aws.core)
    implementation(nvaCatalog.aws.sdk2.http.client)
    implementation(nvaCatalog.commons.lang)
    implementation(nvaLibs.json)
    implementation(platform("software.amazon.awssdk:bom:${nvaCatalog.versions.aws.sdk2.asProvider().get()}"))
    runtimeOnly(libs.jackson.dataformat.hal)
    runtimeOnly(nvaCatalog.log4j.api)
    runtimeOnly(nvaCatalog.log4j.core)
    runtimeOnly(nvaCatalog.log4j.slf4j.impl)
    testImplementation(nvaCatalog.hamcrest)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.mockito.core)
    testImplementation(nvaLibs.testutils)
    testImplementation(nvaLibs.testutils)
}

test {
    environment "ALLOWED_ORIGIN", "*"
    environment "COGNITO_HOST", "https://example.com"
    environment "ELASTICSEARCH_REGION", "eu-west-1"
    environment "BACKUP_BUCKET_NAME", "s3-dummy-name"
    environment "OPENSEARCH_ENDPOINT_PROTOCOL", "http"
    environment "OPENSEARCH_ENDPOINT_ADDRESS", "localhost:3000"
    environment "SCOPE_IDENTIFIER", "https://api.sws.aws.sikt.no/scopes"
    environment "API_GATEWAY_URL", "localhost:8080"
    environment "BACKUP_ROLE_ARN", "arn:aws:s3:::dummy-arn"
    environment "API_HOST", "localhost"
    environment "COGNITO_AUTHORIZER_URLS", "http://localhost:3000"
}
