[versions]
jacksonFormatHal    = { strictly = '1.0.9' }
jsonld              = { strictly = '0.13.6' }

[libraries]
jackson-dataformat-hal           = { group = 'io.openapitools.jackson.dataformat', name = 'jackson-dataformat-hal', version.ref = 'jacksonFormatHal' }
jsonld                           = { group = 'com.github.jsonld-java', name = 'jsonld-java',             version.ref = 'jsonld' }
